### ISSUE TITLE
Can move focus out of modal two 

### ISSUE THREAD

**Issue by danielmatthew** [filamentgroup/fg-modal#1] opened 2020-08-26 15:42 UTC
:wave: I feel bad reporting a bug as the first issue, particularly as it's an otherwise neat implementation:

macOS 10.15.6
Safari 13.1.2 (15609.3.5.1.3)

On opening modal two, I was able to set focus on links in the document behind, which I've hoped to capture in the following gif: 

![2020-08-26 16-35-20 2020-08-26 16_38_09](https://user-images.githubusercontent.com/111794/91324963-918b9a00-e7ba-11ea-81c6-eb863c71f026.gif)

**Comment by tbroyer** [comment] 2020-08-26 15:57
I as about to open an issue about that second modal too, but it is likely the cause of the behavior you reported, so commenting here instead: when opening the second modal, the rest of the page loses its `aria-hidden="true" inert` attributes.

(Chrome 85.0.4183.83 on Linux)

**Comment by scottjehl** [comment] 2020-08-26 16:12
Thanks! Marking this as a bug to fix.

**Comment by scottjehl** [comment] 2020-08-27 16:01
Fixed in master. thanks!

**Closed as completed by scottjehl** 2020-08-27 16:01 UTC
Labels: bug
